name: GitHub-Profile-3D-Contrib

on:
  schedule: # Jalankan setiap 12 jam
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib-action@v1
        with:
          # Ganti 'AhmadAzkia' dengan username GitHub Anda
          github_user_name: AhmadAzkia
          # Pilih tema yang Anda suka (tokyonight, dracula, github_dark, dll.)
          theme: tokyonight 
          
    # Commit file GIF yang baru dibuat ke repositori
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated"
          git push
